import { boolean, decimal, index, int, json, mysqlEnum, mysqlTable, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 128 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export const profiles = mysqlTable("profiles", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), slug: varchar("slug", { length: 80 }).notNull().unique(), githubLogin: varchar("githubLogin", { length: 80 }), githubId: varchar("githubId", { length: 80 }), displayName: varchar("displayName", { length: 180 }), bio: text("bio"), avatarUrl: text("avatarUrl"), location: varchar("location", { length: 180 }), websiteUrl: text("websiteUrl"), isPublic: boolean("isPublic").default(true).notNull(), analyticsConsent: boolean("analyticsConsent").default(true).notNull(), template: varchar("template", { length: 40 }).default("atelier").notNull(), customCss: text("customCss"), sectionConfig: json("sectionConfig"), previewToken: varchar("previewToken", { length: 120 }), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, t => [uniqueIndex("profiles_user_idx").on(t.userId)]);
export const githubConnections = mysqlTable("githubConnections", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), githubId: varchar("githubId", { length: 80 }).notNull(), accessToken: text("accessToken").notNull(), scope: varchar("scope", { length: 255 }), syncedAt: timestamp("syncedAt"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, t => [uniqueIndex("github_user_idx").on(t.userId)]);
export const repositories = mysqlTable("repositories", { id: int("id").autoincrement().primaryKey(), profileId: int("profileId").notNull(), githubRepoId: varchar("githubRepoId", { length: 80 }).notNull(), name: varchar("name", { length: 180 }).notNull(), description: text("description"), language: varchar("language", { length: 80 }), stars: int("stars").default(0).notNull(), forks: int("forks").default(0).notNull(), organizationName: varchar("organizationName", { length: 180 }), topics: json("topics"), isArchived: boolean("isArchived").default(false).notNull(), isFork: boolean("isFork").default(false).notNull(), url: text("url"), homepage: text("homepage"), aiSummary: text("aiSummary"), displayName: varchar("displayName", { length: 180 }), displayDescription: text("displayDescription"), imageUrl: text("imageUrl"), imageKey: varchar("imageKey", { length: 512 }), imageAlt: varchar("imageAlt", { length: 180 }), imageCrop: json("imageCrop"), isPinned: boolean("isPinned").default(false).notNull(), isHidden: boolean("isHidden").default(false).notNull(), sortOrder: int("sortOrder").default(0).notNull(), syncedAt: timestamp("syncedAt").defaultNow().notNull(), lastActivityAt: timestamp("lastActivityAt") }, t => [index("repos_profile_idx").on(t.profileId), uniqueIndex("repo_external_idx").on(t.profileId, t.githubRepoId)]);
export const customDomains = mysqlTable("customDomains", { id: int("id").autoincrement().primaryKey(), profileId: int("profileId").notNull(), domain: varchar("domain", { length: 255 }).notNull().unique(), status: mysqlEnum("status", ["pending", "verified", "active"]).default("pending").notNull(), verificationToken: varchar("verificationToken", { length: 120 }), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const analyticsEvents = mysqlTable("analyticsEvents", { id: int("id").autoincrement().primaryKey(), profileId: int("profileId").notNull(), eventType: varchar("eventType", { length: 40 }).default("pageview").notNull(), visitorHash: varchar("visitorHash", { length: 128 }), country: varchar("country", { length: 80 }), region: varchar("region", { length: 120 }), referrer: text("referrer"), utmSource: varchar("utmSource", { length: 120 }), utmMedium: varchar("utmMedium", { length: 120 }), utmCampaign: varchar("utmCampaign", { length: 160 }), createdAt: timestamp("createdAt").defaultNow().notNull() }, t => [index("analytics_profile_date_idx").on(t.profileId, t.createdAt)]);
export const subscriptions = mysqlTable("subscriptions", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), paddleCustomerId: varchar("paddleCustomerId", { length: 120 }), paddleSubscriptionId: varchar("paddleSubscriptionId", { length: 120 }), plan: mysqlEnum("plan", ["free", "pro", "proPlus"]).default("free").notNull(), status: varchar("status", { length: 40 }).default("inactive").notNull(), managedDomainAddOn: boolean("managedDomainAddOn").default(false).notNull(), managedDomainName: varchar("managedDomainName", { length: 255 }), managedDomainStatus: mysqlEnum("managedDomainStatus", ["none", "requested", "provisioning", "active", "failed"]).default("none").notNull(), renewsAt: timestamp("renewsAt"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, t => [uniqueIndex("subscription_user_idx").on(t.userId)]);

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
