create table if not exists public.users (
  id bigint primary key generated by default as identity,
  "openId" varchar(128) not null unique,
  name text, email varchar(320), "loginMethod" varchar(64),
  role varchar(16) not null default 'user' check (role in ('user','admin')),
  "createdAt" timestamptz not null default now(), "updatedAt" timestamptz not null default now(), "lastSignedIn" timestamptz not null default now()
);

create table if not exists public.profiles (
  id bigint primary key generated by default as identity,
  "userId" bigint not null references public.users(id) on delete cascade,
  slug varchar(80) not null unique, "githubLogin" varchar(80), "githubId" varchar(80), "displayName" varchar(180), bio text, "avatarUrl" text,
  location varchar(180), "websiteUrl" text, "followerCount" integer not null default 0, "followingCount" integer not null default 0,
  "isPublic" boolean not null default true, "analyticsConsent" boolean not null default true, template varchar(40) not null default 'atelier',
  "customCss" text, "sectionConfig" jsonb, "previewToken" varchar(120), "createdAt" timestamptz not null default now(), "updatedAt" timestamptz not null default now(),
  unique("userId")
);

create table if not exists public."githubConnections" (
  id bigint primary key generated by default as identity, "userId" bigint not null references public.users(id) on delete cascade,
  "githubId" varchar(80) not null, "accessToken" text not null, scope varchar(255), "syncedAt" timestamptz,
  "createdAt" timestamptz not null default now(), "updatedAt" timestamptz not null default now(), unique("userId")
);

create table if not exists public.repositories (
  id bigint primary key generated by default as identity, "profileId" bigint not null references public.profiles(id) on delete cascade,
  "githubRepoId" varchar(80) not null, name varchar(180) not null, description text, language varchar(80), stars integer not null default 0, forks integer not null default 0,
  "organizationName" varchar(180), topics jsonb, "isArchived" boolean not null default false, "isFork" boolean not null default false,
  "licenseName" varchar(180), "defaultBranch" varchar(180), "openIssues" integer not null default 0, "openPullRequests" integer not null default 0,
  "contributorCount" integer not null default 0, "latestReleaseTag" varchar(180), "latestReleaseAt" timestamptz, "commitActivity" jsonb, "languageBreakdown" jsonb,
  "healthScore" integer not null default 0, "complexityLevel" varchar(40), "projectCategory" varchar(80), url text, homepage text, "aiSummary" text,
  "displayName" varchar(180), "displayDescription" text, "imageUrl" text, "imageKey" varchar(512), "imageAlt" varchar(180), "imageCrop" jsonb,
  "isPinned" boolean not null default false, "isHidden" boolean not null default false, "sortOrder" integer not null default 0,
  "syncedAt" timestamptz not null default now(), "lastActivityAt" timestamptz, unique("profileId","githubRepoId")
);
create index if not exists repositories_profile_idx on public.repositories("profileId");

create table if not exists public."customDomains" (
  id bigint primary key generated by default as identity, "profileId" bigint not null references public.profiles(id) on delete cascade,
  domain varchar(255) not null unique, status varchar(16) not null default 'pending' check (status in ('pending','verified','active')),
  "verificationToken" varchar(120), "createdAt" timestamptz not null default now(), "updatedAt" timestamptz not null default now()
);

create table if not exists public."contactMessages" (
  id bigint primary key generated by default as identity, "profileId" bigint not null references public.profiles(id) on delete cascade,
  "senderName" varchar(120) not null, "senderEmail" varchar(320) not null, "clientKey" varchar(128) not null, message text not null,
  "spamScore" integer not null default 0, "isRead" boolean not null default false, "createdAt" timestamptz not null default now()
);
create index if not exists contact_profile_date_idx on public."contactMessages"("profileId","createdAt");

create table if not exists public."newsletterSubscriptions" (
  id bigint primary key generated by default as identity, "profileId" bigint not null references public.profiles(id) on delete cascade,
  email varchar(320) not null, status varchar(16) not null default 'active' check (status in ('active','unsubscribed')),
  "unsubscribeToken" varchar(128) not null unique, "createdAt" timestamptz not null default now(), "updatedAt" timestamptz not null default now(), unique("profileId",email)
);

create table if not exists public."analyticsEvents" (
  id bigint primary key generated by default as identity, "profileId" bigint not null references public.profiles(id) on delete cascade,
  "eventType" varchar(40) not null default 'pageview', "visitorHash" varchar(128), country varchar(80), region varchar(120), referrer text,
  "utmSource" varchar(120), "utmMedium" varchar(120), "utmCampaign" varchar(160), "createdAt" timestamptz not null default now()
);
create index if not exists analytics_profile_date_idx on public."analyticsEvents"("profileId","createdAt");

create table if not exists public.subscriptions (
  id bigint primary key generated by default as identity, "userId" bigint not null references public.users(id) on delete cascade,
  "paddleCustomerId" varchar(120), "paddleSubscriptionId" varchar(120), plan varchar(16) not null default 'free' check (plan in ('free','pro','proPlus')),
  status varchar(40) not null default 'inactive', "managedDomainAddOn" boolean not null default false, "managedDomainName" varchar(255),
  "managedDomainStatus" varchar(16) not null default 'none' check ("managedDomainStatus" in ('none','requested','provisioning','active','failed')),
  "renewsAt" timestamptz, "createdAt" timestamptz not null default now(), "updatedAt" timestamptz not null default now(), unique("userId")
);

create table if not exists public."webhookDeliveries" (
  id bigint primary key generated by default as identity, provider varchar(16) not null check (provider in ('paddle','github')),
  "eventId" varchar(180) not null, "eventType" varchar(120) not null, status varchar(40) not null default 'processed', payload text,
  "receivedAt" timestamptz not null default now(), "processedAt" timestamptz not null default now(), unique(provider,"eventId")
);
create index if not exists webhook_provider_date_idx on public."webhookDeliveries"(provider,"receivedAt");
